---
- hosts: db-server
  sudo: yes
  vars:
    dbname: fuel_dev
    dbuser: root
    dbpassword: root
  tasks:
    - name: be sure mysql-server is installed
      yum: name={{item}} state=installed
      with_items:
        - mysql-server
        - MySQL-python
      tags: mysqld

    - name: be sure mysqld is running and enabled
      service: name=mysqld state=started enabled=yes
      tags: mysqld

    - name: Create database
      mysql_db: db={{dbname}} state=present encoding=utf8
      tags: mysqld

    - name: Create database user
      mysql_user: >
        name={{dbuser}}
        password="{{dbpassword}}"
        priv={{dbname}}.*:ALL
        state=present
      tags: mysqld
#  vars_prompt:
#    - name: "dbpassword"
#      prompt: "Please enter MySQL fuel_dev user password"
#      default: "root"
